query ($bucket_slug: String!, $read_key: String, $slug: String) {
  getObjects(
    bucket_slug: $bucket_slug
    read_key: $read_key
    input: { query: { slug: $slug } }
  ) {
    objects {
      id
      title
      slug
      content
      metadata
    }
  }
}
